# Generated by Django 5.2.10 on 2026-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_incus_sync', '0005_incushost_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='incushost',
            name='sync_projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
