# Generated by Django 5.2.10 on 2026-02-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_incus_sync', '0006_incushost_sync_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incushost',
            name='https_url',
        ),
    ]
