# Generated by Django 5.2.10 on 2026-03-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_incus_sync", "0008_incushost_incus_ui_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="incushost",
            name="sync_interval",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
